# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

sudo: required
dist: trusty



before_install:
  - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-full


install:
  - ./run.sh install_aptget r-cran-rmarkdown

script:
  - ./run.sh run_tests

after_failure:
  - ./run.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
